### PR TITLE
Ring Indicator Changes

### PR DESCRIPTION
**Pull request by vaelen**
1. Fixed a small bug in ATS52 and ATS53.
2. Switched RI to default active high.

When RI defaults to active low I am unable to use ATS52 to change the setting, even after my other patch. However, if it is set to default active high, then it works properly. I know this probably isn't best for your use case, but I wanted to bring the issue to your attention.

### CODE REVIEW

**Comment by bozimmerman** [comment]
Ah, ye olde cut-paste errors.  Thanks again.

Couple things:
1. If you are curious, github is a publishing endpoint for me.  My primary source control is a home SVN server that I then automatically push to a local git repo and then to github.  One side-effect is that I can't really pull changes from github at all, which is why I handle PRs here manually and then push them upwards.

2. That RI change would need quite a bit more explanation for me to swallow, starting with:  what is your ESP platform, and what is your host platform?  Is the RS232 level LOW for RI inactive just Wrong?!  Did I miss that in a spec somewhere?

**Comment by vaelen** [comment]
I thought that might be the case (about SVN, I mean). :)

Here is my current setup:
image

I'm using a 30 pin ESP-32 dev board. My dev box is a Windows PC. I've also got a Linux box and a FreeBSD box that I've been using for testing. The serial port is connected to my FreeBSD machine, but it only supports TX/RX. I'm using the LEDs to track the status of the other pins. I'm working on a PCB that will support all the pins.

You're absolutely right, the standard says that all the control lines should be active HIGH, inactive LOW. 

The current code (not including my changes) looks like this:
```
# define DEFAULT_DCD_ACTIVE  LOW
# define DEFAULT_DCD_INACTIVE  HIGH
# define DEFAULT_CTS_ACTIVE  LOW
# define DEFAULT_CTS_INACTIVE  HIGH
# define DEFAULT_RTS_ACTIVE  LOW
# define DEFAULT_RTS_INACTIVE  HIGH
# define DEFAULT_RI_ACTIVE  LOW
# define DEFAULT_RI_INACTIVE  HIGH
# define DEFAULT_DSR_ACTIVE  LOW
# define DEFAULT_DSR_INACTIVE  HIGH
# define DEFAULT_DTR_ACTIVE  LOW
# define DEFAULT_DTR_INACTIVE  HIGH
# define DEFAULT_OTH_ACTIVE  LOW
# define DEFAULT_OTH_INACTIVE  HIGH
```
I'm not sure why the default defines these as active LOW and inactive HIGH.

When I connect to the modem and look at (for example) DCD, I can see that the default settings match the code. The default mode is "1", meaning active LOW inactive HIGH. If I use the modem commands to change this to "0", nothing changes. If I try to force it high by setting it to 2, it instead sets it to 3 "always low". The LEDs I have connected to the pins show that this is indeed what is happening.
```
at&f

Zimodem ESP32 Firmware v4.0.2
sdk=v4.4.7-dirty chipid=3 cpu@240
tot=4096k heap=233k fsize=1287k
INITIALIZED
READY.
OK
ats46
1
OK
ats46=0
OK
ats46
1
OK
ats46=2
OK
ats46
3
OK
```

I swear I tested this yesterday and I was only seeing this behavior on the RI pin, but when I tested it again just now with both the DCD and DTR pins they are both doing the same thing. I double checked, and my code matches your master branch, so maybe I'm just remembering wrong. ¯\_(ツ)_/¯

If I update the code to set the default values to active HIGH, inactive LOW, everything works as expected:
```
# define DEFAULT_DCD_ACTIVE  HIGH
# define DEFAULT_DCD_INACTIVE  LOW
# define DEFAULT_CTS_ACTIVE  HIGH
# define DEFAULT_CTS_INACTIVE  LOW
# define DEFAULT_RTS_ACTIVE  HIGH
# define DEFAULT_RTS_INACTIVE  LOW
# define DEFAULT_RI_ACTIVE  HIGH
# define DEFAULT_RI_INACTIVE  LOW
# define DEFAULT_DSR_ACTIVE  HIGH
# define DEFAULT_DSR_INACTIVE  LOW
# define DEFAULT_DTR_ACTIVE  HIGH
# define DEFAULT_DTR_INACTIVE  LOW
# define DEFAULT_OTH_ACTIVE  HIGH
# define DEFAULT_OTH_INACTIVE  LOW
```

Modem output:
```
at&f

Zimodem ESP32 Firmware v4.0.2
sdk=v4.4.7-dirty chipid=3 cpu@240
tot=4096k heap=284k fsize=1287k
INITIALIZED
READY.
OK
ats46
0
OK
ats46=1
OK
ats46
1
OK
ats46=2
OK
ats46
2
OK
ats46=3
OK
ats46
3
OK
ats46=0
OK
ats46
0
OK
```

**Comment by bozimmerman** [comment]
So, if the orig default levels hadn't been tested and in use since 2018 by so many, I'd be really really terrified right now.

According to some googling though, TTL serial control signals are usually active low...  I couldn't find a general page on the subject, but googling RTS/CTS, and DCD, and finally RI indicated that they were all active low.  This standard goes back to the olde UART chips AFAIK.

"RI [(bar)]: Ring Indicator Pin 39: When low, this indicates that a
telephone ringing signal has been received by the MODEM
or data set..."

Did you find contrary information?

**Comment by vaelen** [comment]
Thanks! I verified on mine that setting those values and reading them back works properly now and that my LEDs act the way I would expect them to.

**Comment by vaelen** [comment]
I get that this works for you and others as active-low, so please consider the rest of this an intellectual discussion, not an ask to change features in your code. I'm more curious about why it's this way than anything else. I'm going to try it with real hardware in both configurations and see which one works in my specific application (details of my application are below).

The RS-232 spec defines the voltage levels for control signals over the wire as a positive voltage (>+3V, but usually in the +12V range) for active and a negative voltage (<-3V, but usually in the -12V range) for inactive. This obviously doesn't work for TTL logic levels of 0V vs +5V, so an RS-232 driver is used to convert these signals to/from the positive/negative voltages needed over the wire (the MAX232N, for example).

From [Wikipedia](https://en.wikipedia.org/wiki/RS-232#Voltage_levels):
> For data transmission lines (TxD, RxD, and their secondary channel equivalents), logic one is represented as a negative voltage and the signal condition is called "mark". Logic zero is signaled with a positive voltage and the signal condition is termed "space". Control signals have the opposite polarity: the asserted or active state is positive voltage and the de-asserted or inactive state is negative voltage. Examples of control lines include request to send (RTS), clear to send (CTS), data terminal ready (DTR), and data set ready (DSR).

From [a report on the RS-232 standard](http://www.bitsavers.org/pdf/datapro/communications_standards/2741_EIA_RS-232-E.pdf):
> Control signals are used to enable and disable data transmission and reception, and to indicate the operational status and condition of the DTE and DCE. A control function is considered to be in the ON condition when the voltage is more positive than +3 volts; it is considered to be in the OFF condition when the voltage is more negative than -3 volts. 

However, the control pins on the 8250 UART and its replacement, the 16550 UART (both used in the IBM PC), use active-low for all control signals. The wiring diagram in the datasheet shows these signals going through an inverter before being sent to the RS-232 driver chip to be converted from 5V to +/-12V. (See the [datasheet for the 16550](https://media.digikey.com/pdf/Data%20Sheets/Texas%20Instruments%20PDFs/PC16550D.pdf), page 26.)

image

(This design seems so stupid to me. Why did they do it this way? I also found that some of the fancier RS-232 driver chips actually have internal inverters.)

I'm guessing that your primary use case is an expansion card that never communicates over an actual cable but instead just communicates directly between the ESP32 and a UART chip on the same expansion card. In that case it would make sense for the signals to be reversed from the ESP32 because there is no RS-232 driver or inverter involved. In my case though, I'm trying to build an external modem that communicates over a cable with early Macs and PCs, so my control logic needs to be active-high. 

We could add a flag to flip all the default values and I can just set that flag in my build, or I could just patch the code to swap the values in my local copy, or I could put an inverter on my board between the ESP32 and the RS-232 driver. All are perfectly good solutions from my perspective. I'll play with it some more and let you know what I find.

**Comment by vaelen** [comment]
Well, I'm just stupid, apparently. The MAX232N has built-in inverters too.

**Comment by vaelen** [comment]
PS: Thanks for helping me catch this before I sent this board to the fab!

**Comment by bozimmerman** [comment]
Hi.

One kind of ironic thing is that older versions of the code had a #define called "RS232_INVERTED" that, when set, makes the control signals active high (+5).  This was for situations when building modems that interface with the Commodore 64, which requires active-high for control signals.

**Pull request closed without merging**
